[package]
name = "example"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.13"
tracing-log = "0.2"

[dependencies.bevy_frame_count_subscriber]
path = "../.."
